### ISSUE TITLE
[Bug] Not able to install and run the Purity Ui Dashboard

### ISSUE THREAD

**Issue by LP440i** [creativetimofficial/purity-ui-dashboard#40]
### Version
current
### Reproduction link
https://jsfiddle.net/z51snw4u/2/
### Operating System
MacOS
### Device
iMac 5K
### Browser & Version
NoBrowser
### Steps to reproduce
1. git clone https://github.com/creativetimofficial/purity-ui-dashboard.git
2. npm install
3. error
### What is expected?
installation of Purity UI Dashboard and then starting it by npm start
### What is actually happening?
the npm install returns thousands of errors.

---
### Solution
I wish I knew.. The link on jsfiddle leads to my log of the errors. I have clean installation of Homebrew, NVM, Node, everything is brand new. Could you please help point me in the right direction to get this functional? Thank you.

**Comment by simmmpleweb** [comment]
Hi, @LP440i! 
Thanks for using our products. It's probably a problem with NPM. I tried reinstalling the project using the same steps and it seems to work fine. Check for any unnecessary package.json files located inside the folder in which you ran the command. Maybe try downloading the .zip of the project and see if the same thing happens.
Regards, Vlad.

**Comment by LP440i** [comment]
Hello, thanks for the info. I did try a few more things but in the end I typed "APM install" instead of "NPM install" by pure accident, it created some node modules directory and it started working.. :D
