### ISSUE TITLE
[Bug] Cannot change "purity-ui-dashboard" from the URL

### ISSUE THREAD

**Issue by iWanheda** [creativetimofficial/purity-ui-dashboard#55]
### Version
latest
### Reproduction link
https://github.com/creativetimofficial/purity-ui-dashboard
### Operating System
Windows
### Device
PC
### Browser & Version
Opera GX latest
### Steps to reproduce
literally download
### What is expected?
somewhere to find the string "purity-ui-dashboard"
### What is actually happening?
found no results leading to "purity-ui-dashboard"

---

**Comment by simmmpleweb** [comment]
Hello, @iWanheda ! Thanks for using our products ! You can change the name of the website from "homepage" inside package.json . Regards, Vlad.
