### ISSUE TITLE
[Bug] Only system fonts are used in theme

### ISSUE THREAD

**Issue by haw0k** [creativetimofficial/purity-ui-dashboard#59]
### Version
2.0.1
### Reproduction link
https://demos.creative-tim.com/purity-ui-dashboard/
### Operating System
elementary OS 6.1 (based on Ubuntu 20.04.5 LTS)
### Device
PC
### Browser & Version
Firefox 104.0.1 (64-bit)
### Steps to reproduce
1. Open link with Purity UI live demo in Firefox at OS without preinstalled fonts Roboto, Helvetica etc.
2. Open Firefox developers tools > Inspector > Fonts > All Fonts on Page
3. Check the fonts list - we can see only system fonts.

next steps reproduces my attempt to adding the Roboto font to local copy of Purity UI  theme:
1. $ git clone https://github.com/creativetimofficial/purity-ui-dashboard
2. $ cd purity-ui-dashboard/
3. $ yarn
4. $ yarn start
5. Open http://localhost:3000/ in Firefox at OS without preinstalled fonts Roboto, Helvetica etc.
6. Open Firefox developers tools > Inspector > Fonts > All Fonts on Page
7. Check the fonts list

### What is expected?
Expect to view 'Roboto' font because src/theme/foundations/fonts.js contains following:
export const font = {
    body: 'Roboto'
};

### What is actually happening?
we can see only preinstalled system fonts: TeX Gyre Heros,  Twemoji Mozilla at my OS

---
### Solution
fix font support (@fontsource/open-sans, @fontsource/raleway, @fontsource/roboto) 
### Additional comments
The same problem is observed in the Pro version of purity-dashboard-react 2.0.2

**Comment by simmmpleweb** [comment]
Hello, @haw0k ! Thanks for using our products. I deleted `fonts.js` entirely, and now if you import the fonts in `index.html`, then set the font in `src/theme/styles.js`, you will no longer face this problem.
<img width="926" alt="Screenshot 2022-09-08 at 19 19 54" src="https://user-images.githubusercontent.com/90040741/189174164-d148d20a-3ab5-4553-a85b-280d387d655b.png">
<img width="1446" alt="Screenshot 2022-09-08 at 19 19 32" src="https://user-images.githubusercontent.com/90040741/189174175-40aa3557-ff5a-4262-950a-107d240e77b8.png">

**Comment by simmmpleweb** [comment]
If there are anymore problems, write us on the discord community! Regards, Vlad.
