### ISSUE TITLE
Build version is not working

### ISSUE THREAD

**Issue by cgrewon** [creativetimofficial/purity-ui-dashboard#60]

**Comment by cgrewon** [comment]
I tried to yarn build and serve -s build, but empty page,

**Comment by simmmpleweb** [comment]
Hello, @cgrewon ! Thanks for using our products! Do you have any errors in the console, or anything that indicates where the error comes from? Try removing the "homepage" from package.json.
Regards, Vlad.

**Comment by simmmpleweb** [comment]
Closed since there was no further details provided.
